### ISSUE TITLE
Error in post processing script

### ISSUE THREAD

**Issue by ghost** [nitinaws/gt-custom-workflow#2]
Hi there,

I get the error:

> An error occurred (AccessDenied) when calling the AssumeRole operation: Access denied: ClientError
> Traceback (most recent call last):
> File "/var/task/sagemaker-gt-postprocess.py", line 102, in lambda_handler
> s3_client = S3Client(role_arn, kms_key_id)
> File "/var/task/s3_helper.py", line 22, in __init__
> assume_role_object = sts_connection.assume_role(RoleArn=role_arn, RoleSessionName=DEFAULT_SESSION)
> File "/var/runtime/botocore/client.py", line 314, in _api_call
> return self._make_api_call(operation_name, kwargs)
> File "/var/runtime/botocore/client.py", line 612, in _make_api_call
> raise error_class(parsed_response, operation_name)
> botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: Access denied

What could it be?

Regards

**Comment by ghost** [comment]
Got the error
